rango/urls.py
from django.conf.urls import url
from rango import views


app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^like/$', views.like_category, name='like_category'),
    # url(r'^login/$', views.user_login, name='login'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    # url(r'^register/$', views.register, name='register'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^profile/(?P<username>[\w\-]+)', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rango import views
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'


urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(blank=True, unique=True)
    
    def save(self, *args, **kwargs):  # Note for self find out wtf this means
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    # Note this error in the book, it's indented
    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Please enter the category name')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Please enter the title of the page')
    url = forms.URLField(max_length=200, help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # Does not work for some reason, ask later
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

    class Meta:
        model = Page
        # Provide an association between the ModelForm and a model
        # What fields do we want?
        # Some fields allow for NULL values so we might not want them
        # Here we hide the foreign key
        # we can exclude fields from the form
        exclude = ('category', )
        # or specify the fields to include.


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        exclude = ('user',)

rango/views.py
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rango.models import Category, Page, UserProfile


def index(request):
    # request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    # Call function to handle the cookies
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    context_dict['last_visit'] = request.session['last_visit']

    # Obtain our Response object early so we can add cookie info.
    response = render(request, 'rango/index.html', context_dict)

    # Return response back to the user and updating cookies
    return response


def about(request):
    context_dict = {'about_site': 'This tutorial has been put together by Jose'}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    context_dict['last_visit'] = request.session['last_visit']
    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    # Create a context dictionary to pass to template
    # Engine
    context_dict = {}
    try:
        # Can we find a category name slug with that name?
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve associated pages
        # Filter will return a list
        pages = Page.objects.filter(category=category)

        # Adds our results to the template page
        context_dict['pages'] = pages
        # We also add the category object from
        # The database to the context dictionary
        # We'll use this in the template to verify that category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if there's no category
        # Don't do anything
        context_dict['category'] = None
        context_dict['pages'] = None
    if request.method == 'POST':
        query = request.POST['query']
        results = Page.objects.filter(title__icontains=query)
        context_dict['result_list'] = results
    return render(request, 'rango/category.html', context=context_dict)


def add_category(request):
    form = CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database
            form.save(commit=True)
            # Now that the category is saved
            # We could give a confirmation message
            # But since the most recent category added is on the index page
            # Then we can direct the user back to the index page.
            return index(request)
        else:
            # The supplied form contains errors
            # Just print them to terminal
            print(form.errors)
        # Will handle the bad form, new form or no form supplied cases.
        # Render the form with error messages (if any)
    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

'''
def register(request):
    # A boolean field for telling the template
    # Whether the registration was successful
    # Set to False initially. Code changes value to
    # True when registration is successful
    registered = False

    # If it's a HTTP POST, we're registering data
    if request.method == 'POST':
        # Attempt to grab information from the raw form information
        # Note that the we use both forms.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            # Save data to db
            user = user_form.save()
            # Hash the password
            # Once hashed we can update the user object
            user.set_password(user.password)
            user.save()

            # Now sorting the UserProfile
            # Since we need to set the user attribute ourselves
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile
            profile.save()

            # Update our variable to indicate the template registration was successful
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not an HTTP POST, so render the two ModelForm instances
        # Blank forms
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context
    return render(request, 'rango/register.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })

def user_login(request):
    # If the request is POST, pull info
    fail_auth = False
    if request.method == 'POST':
        # Gather userrname and password
        # This information is obtained from the form
        # We use request.POST.get(variable) as opposed
        # to request.POST[variable] because
        # request.POST.get returns None
        # if it does not exist
        # while request.POST[]
        # raises a keyError
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct
        # If None, no user with matching credentials
        if user:
            # Is the account active? It could be disabled/banned
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse('Your rango account is disabled')
        else:
            # Bad login details were provided. So we can't log the user in
            print("Invalid login details: {0},{1}".format(username, password))
            fail_auth = True
            return render(request, 'rango/login.html', {'fail_auth': fail_auth})

    # The request method is not HTTP POST so display the login form.
    # This scenario would most likely be HTTP GET
    else:
        # No context variable to pass to the template system, hence the
        # blank directory object...
        return render(request, 'rango/login.html', {})

# Use login required decorator to ensure only logged in users can log out
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
'''

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


# def visitor_cookie_handler(request, response):
def visitor_cookie_handler(request):
    # Get the number of visits to the site.
    # We use the COOKIES.get() function to obtain the visits cookie.
    # If the cookie exists, the vale returned is casted to int.
    # If the cookie doesn't exist it defaults to 1
    visits = int(request.COOKIES.get('visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    # last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now())) Old version
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        # update the last visit cookie now that the count is updated
        # response.set_cookie('last_visit', str(datetime.now())) Old Version
        request.session['last_visit'] = str(datetime.now())
    else:
        # set the last visit cookie
        # response.set_cookie('last_visit', last_visit_cookie)
        request.session['last_visit'] = last_visit_cookie

    # Update/set the visits cookie
    request.session['visits'] = visits


def search(request):
    result_list = []

templates/rango/about.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <p>You've visited this site: {{ visits }}  time{% if visits > 1 %}s{% endif %}</p>
    <p>Your last visit was on: {{ last_visit }}</p>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    {{ about_site }}
    <button class="btn btn-primary" onclick="alert('You clicked the button using JS');">
    Click me - I run Javascript
    </button>
    <button class="btn btn-primary" id="about-btn">
        Click Me - I'm JavaScript on Speed
    </button>
    <p>This tesxt is for Jquery example.</p>
    <div id="msg">Hello - I'm here for a JQuery Example too</div>
    <img src="{{ MEDIA_URL }}catanddog.jpg">
    <a href="/rango/">Go back to index.</a>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}Add Category{% endblock %}

{% block body_block %}
    <h2 class="form-signin-heading">Add a category</h2>
    <div>
        <form role="form" id="category_form" method="post" action="/rango/add_category/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
            {% endfor %}
            <button class="btn btn-primary" type="submit" name="submit">Add a Category</button>
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}Add Page{% endblock %}

{% block body_block %}
    {% if category %}
    <form role="form" id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
    <h2 class="form-signin-heading">Add a page to <a href="/rango/category/{{ category.slug }}">{{ category.name }}</a></h2>
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br />
        {{ field }}<br />
    {% endfor %}
    <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
    </form>
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %} <!-- Report that in Django 1.10 if app name, needs to be rango:show_categories -->
        {% endblock %}
    </div>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            {% else %}
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                <li><a href="{% url 'registration_register' %}">Register</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
</body>
</html>

templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico">
    <title>Rango - {% block title %} How to Tango with Django {% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
      <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rango</a>
      <div id="navbar">
        <nav class="nav navbar-nav pull-xs-left">
          <a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
          {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
              <a class="nav-item nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'auth_logout' %}?=next=/rango/">Logout</a>
              <a class="nav-item nav-link" href="{% url 'rango:list_profiles' %}">Profile List</a>
          {% else %}
              <a class="nav-item nav-link" href="{% url 'registration_register' %}">Register Here</a>
              <a class="nav-item nav-link" href="{% url 'auth_login' %}">Login</a>
          {% endif %}
          <a class="nav-item nav-link" href="#">Help</a>
        </nav>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-list">
                <li class="nav-header">Type to find a category</li>
                <form>
                    <li><input class="search-query form-control" type="text" name="suggestion" value="" id="suggestion" /></li>
                </form>
            </ul>
        <hr />
        <div id="cats">
        </div>


        {% comment %}
            {% block sidebar_block %}
                <input class="input-medium search-query" type="text" name="suggestion" value="" id="suggestion" />
                <h1>Test</h1>
                {% get_category_list category %}
            {% endblock %}
       {% endcomment %}


        </div>
      <!-- Note the way to write the offset-->
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            {% block body_block %}{% endblock %}
        </div>
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="{% static "js/rango-jquery.js" %}"></script>
    <script src="{% static "js/rango-ajax.js" %}"></script>
    <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}



    {% if user.is_authenticated %}
    <h1>Search with Rango</h1>
        <br />
        <form class="form-inline" id="user_form" method="post" action="{% url 'rango:show_category' category.slug %}">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" size="50" name="query" value="" id="query" />
            </div>
            <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
        </form>
    {% endif %}



    {% if user.is_authenticated %}
        <button class="btn btn-primary btn-sm" id="likes" data-catid="{{ category.id }}"> Like </button>
        <div id="like_count">{{ category.likes }}</div>
    {% endif %}


    <div>
        {% if result_list %}
          <h3>Results</h3>
          <div class="list-group">
            {% for result in result_list %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="{{ result.link }}">{{ result.title }}</a>
                    </h4>
                    <p class="list-group-item-text">{{ result.summary }}</p>
                </div>
            {% endfor %}
          </div>
        {% endif %}
    </div>
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}"> {{ page.title }} </a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category</strong>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
    {% if category %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act.cat %}
                <li>
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}
{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
        <h1 class="display-3">Rango says...</h1>
        {% if user.is_authenticated %}
            <h1>Hey there {{ user.username }}</h1>
        {% else %}
            <h1>Hey there partner!</h1>
        {% endif %}
    </div>
    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Most Liked Categories</h4>
            <p>
                {% if categories %}
                    <ul class="list-group">
                    {% for category in categories %}
                    <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                        <span class="tag tag-pills tag-primary">{{ category.likes }}</span>
                    </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}
            </p>
        </div>
        <div class="col-lg-6">
            <h4>Most Viewed Pages</h4>
            <p>
                {% if pages %}
                    <ul class="list-group">
                    {% for page in pages %}
                        <li class="list-group-item">
                            <a href="{% url 'rango:goto' %}?page_id={{ page.id }}"> {{ page.title }} </a>
                            <span class="tag tag-pills tag-primary">{{ page.likes }}</span>
                        </li>
                    {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no pages present.</strong>
                {% endif %}
            </p>
        </div>
    </div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango">
{% endblock %}

templates/rango/login.html
{% extends 'rango/base_bootstrap.html.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css" rel="stylesheet">
    <div class="jumbotron">
        <h1 class="display-3">Login</h1>
    </div>

<form class="form-signin" role="form" method="post" action=".">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text"
</form>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
<!-- Remember to create my own form -->
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/old-login.html
{% extends 'rango/base_bootstrap.html.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<form id="login_form" method="post" action="{% url 'rango:login' %}">
<!-- Remember to create my own form -->
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Registration Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage</a>
    {% else %}
        Rango says: <strong>register here!</strong>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- Display both forms -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <p>This is a a restricted view: <strong>{{ user.username }}</strong></p>
{% endblock %}

templates/rango/search.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title %} Search {% endblock %}

{% block body_block %}
    <div>
        <h1>Search with Rango</h1>
        <br />
        <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" size="50" name="query" value="" id="query" />
            </div>
            <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
        </form>
    <div>
        {% if result_list %}
          <h3>Results</h3>
          <div class="list-group">
            {% for result in result_list %}
                <div class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <a href="{{ result.link }}">{{ result.title }}</a>
                    </h4>
                    <p class="list-group-item-text">{{ result.summary }}</p>
                </div>
            {% endfor %}
          </div>
        {% endif %}
    </div>
</div>
{% endblock %}